server:
  port: 8090

spring:
  application:
    name: web-application-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/csdn
    username: root
    password: Zyq@2019
    name: csdn
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: message_zh_CN

mybatis:
  mapper-locations:
    - mybatis/mysql/*.xml

logging:
  path: ./logs
  file: demo-web
  level:
    root: INFO

  config: classpath:main-logback.xml

